version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ai_ecommerce
    ports:
      - "3306:3306"
